### ISSUE TITLE
Wände müssen vor Explosionen schützen

### ISSUE THREAD

**Issue by rokkbert** [eauw/bomberman-server#19]
Explodierende Bomben dürfen nicht durch Wände hindurch wirken, auch nicht durch zerstörbare Wände.
Beispiel, Ausgangssituation, Bombe der Stärke 3:
.|.|p|w|w|B|.|.|.|.
Wenn die Bombe hochgeht:
falsch: .|.|*|*|*|*|*|*|*|.
richtig: .|.|p|w|*|*|*|*|*|.
D.h. auch hinter w-Wänden soll man sich verstecken können.

**Comment by eauw** [comment]
Gefixt.
