### ISSUE TITLE
Server muss doppelte Namen verhindern.

### ISSUE THREAD

**Issue by rokkbert** [eauw/bomberman-server#20]
Wenn sich ein Client verbindet und seinen Namen in einen Namen ändern will, der schon vergeben ist, dann muss der Server das verhindern. Sonst hat man in der Liste der Spieler doppelte Namen und kann die Spieler nicht auseinanderhalten.
Mögliche Lösungen:
1. der Server lehnt die Änderung einfach ab (mit Fehlermeldung) und der Name bleibt unverändert (i.d.R. also dann so was wie "Player3").
2. der Server verändert den gewünschten Namen so, dass er Eindeutig ist (z.B. "SuperBot" -> "SuperBot2").

**Comment by eauw** [comment]
Da der Spieler nun jederzeit seinen Namen ändern kann setze ich der einfachheithalber Lösung 1 um.
