### ISSUE TITLE
Minimale Wartezeit bzw. maximale Geschwindigkeit

### ISSUE THREAD

**Issue by rokkbert** [eauw/bomberman-server#21]
Nice to have:
Es wäre gut, wenn der Server einen Parameter für die maximale Geschwindigkeit hätte, und nicht nur den timeout, wie lange eine Runde maximal dauert. Wenn alle Spieler sehr schnell sind dann hat man sonst keine Möglichkeit, überhaupt zu sehen, was abgeht. Gut wäre also so etwas wie "-maxSpeed 100", wobei die 100 dann Millisekunden wären. Den Clients braucht das nicht mitgeteilt zu werden, da sie ohnehin nicht davon ausgehen können, dass eine Runde schnell vorbei ist, weil jeder andere Spieler sich beliebig Zeit bis zum Timeout lassen könnte.

**Comment by eauw** [comment]
Ich hab das eingebaut, allerdings mintimout genannt :-/
